Credits: https://github.com/bansalkanav/Machine_Learning_and_Deep_Learning

# High Speed Numerical Array Computation using `Numpy Module`

## Installing Numpy and Numpy Array Creation

In [2]:
# Install a pip package in the current Jupyter kernel
! pip install numpy

In [2]:
lst = [1, 2, 3, 4, 5, 6, 7]

print(type(lst))

print("List: ", lst)

<class 'list'>
List:  [1, 2, 3, 4, 5, 6, 7]


In [3]:
import numpy as np

arr = np.array(lst)

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4 5 6 7]


In [4]:
# Creating a simple array in numpy

arr = np.array([1, 2, 3, 4])

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4]


In [5]:
# Creating a simple array in numpy using np.arange

arr = np.arange(10)

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [0 1 2 3 4 5 6 7 8 9]


## Why Numpy?

- Most powerful numerical processing library in python. Array Oriented computing.
- Provides extension package to python for multi dimensional array.
- Very efficient.
- Scientific computation.

# But WHY numpy, when we already have  lists?

In [6]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i];

Wall time: 318 ms


In [7]:
%%time

arr = np.arange(1000000)

arr = arr * arr

Wall time: 3.99 ms


## Numpy Array and It's Attributes/Properties

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4]
Shape:  (4,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Data Type:  int32
Item Size:  4
Dimensionality:  2


## Functions for creating Numpy Array

In [21]:
arr = np.arange(10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape:  (10,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [22]:
arr = np.arange(1, 10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [23]:
arr = np.arange(1, 10, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 3 5 7 9]
Shape:  (5,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [17]:
arr = np.ones((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [18]:
arr = np.zeros((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [19]:
arr = np.eye(3)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [20]:
arr = np.eye(3, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape:  (3, 2)
Data Type:  float64
Item Size:  8
Dimensionality:  2


## Numpy Random Numbers

1. **np.random.rand** - generates an array with random numbers that are uniformly distribute between 0 and 1.
2. **np.random.randn** - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
3. **np.random.randint** - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
4. **np.random.uniform** - generates an array with random numbers (float) between given numbers.

In [1]:
# Randomly generate an array from uniform distribution
import numpy as np

arr = np.random.rand(5)

print("Numpy Array: \n", arr)

Numpy Array: [0.99874817 0.57202583 0.09257458 0.95423974 0.84808762]


In [2]:
# Randomly generate an array with 10 rows and 2 columns
arr = np.random.rand(10, 2)

print("Numpy Array generated randomly from uniform distribution: \n", arr)

Numpy Array: 
 [[0.95058724 0.34751559]
 [0.45003974 0.4435292 ]
 [0.84246695 0.07034285]
 [0.94661793 0.17819281]
 [0.65273572 0.63094778]
 [0.81592164 0.394703  ]
 [0.48350534 0.70502715]
 [0.92465735 0.1957765 ]
 [0.9910705  0.17333839]
 [0.82353723 0.21145544]]


In [3]:
# Randomly generate an array from normal distribution
import numpy as np

arr = np.random.randn(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [-1.02823844  1.5711288  -0.32093394 -2.06807394  0.41931865]


In [4]:
# Randomly generate an array with 5 rows and 4 columns
arr = np.random.randn(5, 4)

print("Numpy Array generated randomly from normal distribution: \n", arr)

Numpy Array generated randomly from normal distribution: 
 [[ 2.04869375  0.55441342 -1.44393879  0.75913208]
 [-0.66111753 -0.92596042 -1.23111625  0.48700794]
 [-0.96505324 -0.05800912 -0.44525674  0.44425931]
 [-0.33507736 -0.08101463  1.40252771  1.21320381]
 [-0.20986934 -1.81415379 -0.54586554  1.10574333]]


In [5]:
# Generate one random integer between 0 to 9

value = np.random.randint(10)

print(value)

4


In [6]:
# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[0 0 3 0]
 [7 5 6 1]
 [9 9 2 3]
 [0 8 2 3]
 [2 9 2 6]]


In [8]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[31 35 14 17 39 28 13 26 20 16]
 [37 26 27 32 18 25 37 26 29 17]
 [12 19 37 16 32 11 14 21 23 10]
 [11 21 31 18 24 14 12 20 38 39]
 [32 21 35 26 19 39 34 33 38 32]]


In [10]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)

print(value)

2.4128744779031948


In [11]:
# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[1.01920594 1.64120998 5.51465259 4.09812238]
 [7.19145947 6.04636853 7.25114744 9.97129873]
 [8.4901318  8.65173547 6.72373219 8.14324701]
 [3.23774515 3.94731998 6.74261122 8.59192228]
 [9.12520478 3.05433765 8.5485818  4.08424292]]


In [13]:
# Randomly generate a 5*3 array containing values in the range of 10 to 40
arr = np.random.uniform(10, 40, size = (5, 3))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[31.96582082 35.45326888 32.18998882]
 [35.63616462 10.0007978  38.40264923]
 [27.73639873 14.34154597 18.23747816]
 [24.78090733 35.22426243 33.88426754]
 [22.72896987 10.0317634  17.64568205]]


## Numpy Array - Indexing, Slicing and Updating

Since data in numpy array is **stored sequentially**, it is possible to access the data with the help of **Indexing** and **Slicing** operation. NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, **arrays can be indexed by arrays of integers and arrays of booleans**.

Also remember that **numpy array's are mutable**. i.e. Data stored in numpy array can be updated/changed.

#### Data Accessing using `Indexing` in Numpy Array

In [19]:
# Randomly generating 1 dimensional array
arr = np.random.randint(100, size = (5, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [69 99 41 93 68]
Shape:  (5,)


In [20]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  41


In [21]:
# Accessing 5th index
print("Value at 5th index: ", arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [32]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[72 43 62 23]
 [26  5 17 35]
 [63 61  5 85]
 [96 34 79 53]
 [93 24 89 80]]


In [33]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  [63 61  5 85]


In [34]:
# Accessing value at 2, 1 index
print("Accessing Value using Way-1: ", arr[2][1])

print("Accessing Value using Way-2: ", arr[2, 1]) 
# Way-2 syntax can be helpful to access multiple values

Accessing Value using Way-1:  61
Accessing Value using Way-2:  61


In [35]:
# Accesssing multiple values
print(arr[[2, 1], [1, 1]])

[61  5]


#### Data Accessing using `Slicing` in Numpy Array

In [37]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [21 31 53 94 12 74 98 33 74 54]
Shape:  (10,)


In [38]:
# print(arr[1:4])

# print(arr[0:-4])

# print(arr[::2])

In [40]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape:  (3, 4)


In [43]:
# # Remember Way-2 for accessing the data in Numpy array
# print(arr[:2, 1:3])

In [44]:
# print(arr[1:2, :])

#### Indexing with Boolean Arrays

In [89]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [27 32 82 91 31 75  9 72 30 98]
Shape:  (10,)


In [90]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[27 75 30 98]


#### Updating Data in Numpy Array

In [36]:
# Updating value in the array

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[72 43 62 23]
 [26  5 17 35]
 [63 61  5 85]
 [96 34 79 53]
 [93 24 89 80]]
Updated Array: 
 [[72 43 62 23]
 [26 99 17 35]
 [63 61  5 85]
 [96 34 79 53]
 [93 24 89 80]]


## Numpy Flatten and Ravel

In [49]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[21 31 26 28 22 32 27 15 25 31]
 [20 11 10 11 27 20 23 29 19 35]
 [32 39 13 17 31 17 12 21 11 38]
 [28 27 17 18 30 30 29 16 15 27]
 [28 13 38 37 27 24 18 25 27 24]]
Shape:  (5, 10)


In [53]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [21 31 26 28 22 32 27 15 25 31 20 11 10 11 27 20 23 29 19 35 32 39 13 17
 31 17 12 21 11 38 28 27 17 18 30 30 29 16 15 27 28 13 38 37 27 24 18 25
 27 24]
Shape:  (50,)


In [54]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [21 31 26 28 22 32 27 15 25 31 20 11 10 11 27 20 23 29 19 35 32 39 13 17
 31 17 12 21 11 38 28 27 17 18 30 30 29 16 15 27 28 13 38 37 27 24 18 25
 27 24]
Shape:  (50,)


#### Look's like both are performing fatten operation on the array data. But is there any difference between two functions?

In [55]:
# Updating value in the array
print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[21 31 26 28 22 32 27 15 25 31]
 [20 11 10 11 27 20 23 29 19 35]
 [32 39 13 17 31 17 12 21 11 38]
 [28 27 17 18 30 30 29 16 15 27]
 [28 13 38 37 27 24 18 25 27 24]]
Updated Array: 
 [[21 31 26 28 22 32 27 15 25 31]
 [20 99 10 11 27 20 23 29 19 35]
 [32 39 13 17 31 17 12 21 11 38]
 [28 27 17 18 30 30 29 16 15 27]
 [28 13 38 37 27 24 18 25 27 24]]


In [56]:
print("Flatten Array: \n", flatten_arr)

print("Ravel Array: \n", ravel_arr)

Flatten Array: 
 [21 31 26 28 22 32 27 15 25 31 20 11 10 11 27 20 23 29 19 35 32 39 13 17
 31 17 12 21 11 38 28 27 17 18 30 30 29 16 15 27 28 13 38 37 27 24 18 25
 27 24]
Ravel Array: 
 [21 31 26 28 22 32 27 15 25 31 20 99 10 11 27 20 23 29 19 35 32 39 13 17
 31 17 12 21 11 38 28 27 17 18 30 30 29 16 15 27 28 13 38 37 27 24 18 25
 27 24]


#### Observation
Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

## Numpy Reshape

In [59]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[36 20 19 16 21 36 31 39 34 18]
 [37 33 30 38 12 17 29 34 17 19]
 [17 33 39 27 32 37 30 18 16 15]
 [33 27 22 19 32 20 38 19 26 37]
 [13 11 24 34 28 26 28 12 28 22]]
Shape:  (5, 10)


In [63]:
arr_reshaped = arr.reshape(10, 5)

print(arr_reshaped)

[[36 20 19 16 21]
 [36 31 39 34 18]
 [37 33 30 38 12]
 [17 29 34 17 19]
 [17 33 39 27 32]
 [37 30 18 16 15]
 [33 27 22 19 32]
 [20 38 19 26 37]
 [13 11 24 34 28]
 [26 28 12 28 22]]


In [64]:
arr_reshaped = arr.reshape(25, 2)

print(arr_reshaped)

[[36 20]
 [19 16]
 [21 36]
 [31 39]
 [34 18]
 [37 33]
 [30 38]
 [12 17]
 [29 34]
 [17 19]
 [17 33]
 [39 27]
 [32 37]
 [30 18]
 [16 15]
 [33 27]
 [22 19]
 [32 20]
 [38 19]
 [26 37]
 [13 11]
 [24 34]
 [28 26]
 [28 12]
 [28 22]]


In [65]:
# arr_reshaped = arr.reshape(3, 3)

# print(arr_reshaped)

In [66]:
# arr_reshaped = arr.reshape(5, 50)

# print(arr_reshaped)

## Iterating over Numpy Array

#### Iterating over a 1 Dimensional Array

In [69]:
# Randomly generate an array containing values in the range of 10 to 39
arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [38 28 21 18 29 11 26 34 32 16]
Shape:  (10,)


In [71]:
# Looping over items in the array
for item in arr1d:
    print(item, end=" ")

38 28 21 18 29 11 26 34 32 16 

#### Iterating over a 2 Dimensional Array

In [72]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr2d = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr2d)

print("Shape: ", arr2d.shape)

Numpy Array: 
 [[29 23 30 32 15 36 34 21 23 24]
 [35 31 20 38 22 30 14 29 33 33]
 [14 14 36 11 37 10 17 14 35 23]
 [38 27 10 14 33 36 17 14 26 17]
 [27 38 27 30 19 34 16 29 33 16]]
Shape:  (5, 10)


In [74]:
# Looping over rows in the 2d array
for row in arr2d:
    print(row)

[29 23 30 32 15 36 34 21 23 24]
[35 31 20 38 22 30 14 29 33 33]
[14 14 36 11 37 10 17 14 35 23]
[38 27 10 14 33 36 17 14 26 17]
[27 38 27 30 19 34 16 29 33 16]


In [76]:
# Looping over each item in the 2d array
for item in arr2d.ravel():
    print(item, end=" ")

29 23 30 32 15 36 34 21 23 24 35 31 20 38 22 30 14 29 33 33 14 14 36 11 37 10 17 14 35 23 38 27 10 14 33 36 17 14 26 17 27 38 27 30 19 34 16 29 33 16 

#### Excercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Using a Loop)

In [77]:
# Code

## Python Operators on Numpy Array

In [95]:
# We can apply any python operator on Numpy Array.
# It will perform the operation on each element of a numpy array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

Original Array: 
 [[1 2 3]
 [4 5 6]]


In [99]:
print(x + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [100]:
print(x % 2)

[[1 0 1]
 [0 1 0]]


In [102]:
print(x >= 3)

[[False False  True]
 [ True  True  True]]


In [103]:
print(x % 2 == 0)

[[False  True False]
 [ True False  True]]


#### Excercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Without using a Loop)

In [105]:
# Code

## Numpy Maths

Reference: https://numpy.org/doc/stable/reference/routines.math.html

In [86]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [87]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))

print("Exponent: ", np.exp(arr))

print("Trigonometric Sin: ", np.sin(arr))

print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [39]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [38]:
# Matrix Multiplication

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]


In [78]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


In [92]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


## Numpy Statistics

In [24]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise

print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Array: 
 [1 3 5 7 9]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [41]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise

print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [42]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [43]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Maximum:  6
Mean:  3.5
Median:  3.5
Variance:  2.9166666666666665
Std Dev:  1.707825127659933


In [55]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

## Miscellaneous Topics

#### Linspace

In [13]:
# Syntax => np.linspace(begin, end, # of elements)

print(np.linspace(1, 5, 9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [14]:
print(np.linspace(10,13,6))

[10.  10.6 11.2 11.8 12.4 13. ]


#### Sorting

In [7]:
arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[89 98 58 70 88 69 84 88 81 52]
 [57 76 83 53 60 92 82 81 74 70]
 [75 89 84 86 81 62 84 54 69 51]
 [87 98 76 72 87 73 52 84 61 57]
 [77 94 90 53 60 58 88 77 96 56]]


In [8]:
# Column Wise Sorting

np.sort(arr, axis = 0)

array([[57, 76, 58, 53, 60, 58, 52, 54, 61, 51],
       [75, 89, 76, 53, 60, 62, 82, 77, 69, 52],
       [77, 94, 83, 70, 81, 69, 84, 81, 74, 56],
       [87, 98, 84, 72, 87, 73, 84, 84, 81, 57],
       [89, 98, 90, 86, 88, 92, 88, 88, 96, 70]])

In [9]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[52, 58, 69, 70, 81, 84, 88, 88, 89, 98],
       [53, 57, 60, 70, 74, 76, 81, 82, 83, 92],
       [51, 54, 62, 69, 75, 81, 84, 84, 86, 89],
       [52, 57, 61, 72, 73, 76, 84, 87, 87, 98],
       [53, 56, 58, 60, 77, 77, 88, 90, 94, 96]])

#### Stacking

In [11]:
arr1 = np.arange(5,15).reshape(2,5)
print(arr1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
arr2 = np.arange(25,35).reshape(2,5)
print(arr2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [13]:
np.vstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [18]:
np.hstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Concatenate

In [20]:
np.concatenate([arr1, arr2], axis = 0) # adding row wise

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [16]:
np.concatenate([arr1, arr2], axis = 1) # adding Column wise

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Append

In [21]:
np.append(arr1, arr2, axis = 0) # adding row wise

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [22]:
np.append(arr1, arr2, axis = 1) # adding Column wise

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Where

In [24]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [27]:
np.where(arr > 64, 0, arr)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [28]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

### argsort

In [1]:
import numpy as np

arr = np.array([10, -5, 6, -1])

print(arr.argsort()) # Returns indexes

print(arr[arr.argsort()])

[1 3 2 0]
[-5 -1  6 10]


## Numpy Broadcasting

* Start matching the dimensions backward (Right to Left)
    - Compatible - If same number appears or if one of them is 1
    - Incompatible - Otherwise

In [2]:
import numpy as np

In [3]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [4]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([[1], [2]])

print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]


In [5]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1])

print(arr_1 + arr_2)

[[2 3 4]
 [5 6 7]]


In [6]:
arr_1 = np.array([1, 2, 3, 4, 5])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [7]:
arr_1 = np.array([[1], [2], [3], [4], [5]])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
