Credits: https://github.com/bansalkanav/Machine_Learning_and_Deep_Learning

# High Speed Numerical Array Computation using `Numpy Module`

## Installing Numpy and Numpy Array Creation

In [2]:
# Install a pip package in the current Jupyter kernel
! pip install numpy

In [3]:
lst = [1, 2, 3, 4, 5, 6, 7]

print(type(lst))

print("List: ", lst)

<class 'list'>
List:  [1, 2, 3, 4, 5, 6, 7]


In [4]:
import numpy as np

arr = np.array(lst)

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4 5 6 7]


In [5]:
# Creating a simple array in numpy

arr = np.array([1, 2, 3, 4])

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4]


In [6]:
# Creating a simple array in numpy using np.arange

arr = np.arange(10)

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [0 1 2 3 4 5 6 7 8 9]


## Why Numpy?

- Most powerful numerical processing library in python. Array Oriented computing.
- Provides extension package to python for multi dimensional array.
- Very efficient.
- Scientific computation.

# But WHY numpy, when we already have  lists?

In [9]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i];

Wall time: 520 ms


In [10]:
%%time

arr = np.arange(1000000)

arr = arr * arr

Wall time: 11 ms


## Numpy Array and It's Attributes/Properties

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4]
Shape:  (4,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Data Type:  int32
Item Size:  4
Dimensionality:  2


## Functions for creating Numpy Array

In [13]:
arr = np.arange(10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape:  (10,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [14]:
arr = np.arange(1, 10)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [15]:
arr = np.arange(1, 10, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 3 5 7 9]
Shape:  (5,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [16]:
arr = np.ones((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [17]:
arr = np.zeros((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [18]:
arr = np.eye(3)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [19]:
arr = np.eye(3, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape:  (3, 2)
Data Type:  float64
Item Size:  8
Dimensionality:  2


## Datatypes in Numpy

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- str - string
- f - float
- m - timedelta
- M - datetime
- O - object
- u - unsigned integer
- c - complex float
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [13]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='f')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2. 1. 4. 5.]
Data Type:  float32


In [15]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='O')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  object


In [17]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='str')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 ['2' '1' '4' '5']
Data Type:  <U1


## Numpy Random Numbers

1. **np.random.rand** - generates an array with random numbers that are uniformly distribute between 0 and 1.
2. **np.random.randn** - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
3. **np.random.randint** - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
4. **np.random.uniform** - generates an array with random numbers (float) between given numbers.

In [20]:
# Randomly generate an array from uniform distribution
import numpy as np

arr = np.random.rand(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [0.82836615 0.06301418 0.35701122 0.57106337 0.74289751]


In [21]:
# Randomly generate an array with 10 rows and 2 columns
arr = np.random.rand(10, 2)

print("Numpy Array generated randomly from uniform distribution: \n", arr)

Numpy Array generated randomly from uniform distribution: 
 [[0.14780062 0.17471453]
 [0.11369732 0.75176273]
 [0.24432784 0.88829167]
 [0.19609728 0.79319541]
 [0.64327064 0.52992433]
 [0.70977242 0.98405821]
 [0.47159476 0.54128465]
 [0.59540315 0.33811901]
 [0.05437257 0.91444331]
 [0.7751666  0.40268502]]


In [22]:
# Randomly generate an array from normal distribution
import numpy as np

arr = np.random.randn(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [ 0.49839533 -1.11310584  0.19360978  0.80252796 -0.59723223]


In [23]:
# Randomly generate an array with 5 rows and 4 columns
arr = np.random.randn(5, 4)

print("Numpy Array generated randomly from normal distribution: \n", arr)

Numpy Array generated randomly from normal distribution: 
 [[ 0.3276004   0.65298936 -0.34492366 -0.40719086]
 [-0.84149979  1.24736407 -1.65994873 -0.74336453]
 [ 0.51983285  0.42959454  0.2538706   2.13430918]
 [ 0.08714018 -0.57434726 -0.66789889  0.04031373]
 [-0.39606974  0.03331962  0.27393002 -1.24712954]]


In [24]:
# Generate one random integer between 0 to 9

value = np.random.randint(10)

print(value)

0


In [25]:
# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[8 5 5 5]
 [3 1 3 7]
 [0 0 1 1]
 [9 5 3 6]
 [5 3 9 0]]


In [26]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[19 34 38 10 18 27 27 37 36 29]
 [26 19 19 15 21 25 30 34 38 30]
 [23 10 25 34 18 39 24 26 25 22]
 [36 10 23 39 16 28 35 10 22 18]
 [37 13 36 34 30 33 32 37 38 11]]


In [27]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)

print(value)

8.208142773056082


In [28]:
# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[1.08645919 6.99780372 9.3472326  1.78444655]
 [9.44252538 2.34501493 5.61920347 7.43719881]
 [9.52631199 5.14569691 5.4363398  1.02344593]
 [7.80693877 5.89343685 4.63857927 8.68612154]
 [1.90823285 2.31590231 5.2456755  9.03484739]]


In [29]:
# Randomly generate a 5*3 array containing values in the range of 10 to 40
arr = np.random.uniform(10, 40, size = (5, 3))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[22.05211375 19.63663591 25.85448062]
 [13.64502298 18.7925905  12.78952453]
 [26.19022358 19.38307581 20.59128571]
 [32.65337646 33.9344369  23.85014336]
 [30.83100912 14.24930461 15.1472414 ]]


## Numpy Array - Indexing, Slicing and Updating

Since data in numpy array is **stored sequentially**, it is possible to access the data with the help of **Indexing** and **Slicing** operation. NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, **arrays can be indexed by arrays of integers and arrays of booleans**.

Also remember that **numpy array's are mutable**. i.e. Data stored in numpy array can be updated/changed.

#### Data Accessing using `Indexing` in Numpy Array

In [30]:
# Randomly generating 1 dimensional array
arr = np.random.randint(100, size = (5, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [ 1 98 59 28 12]
Shape:  (5,)


In [31]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  59


In [32]:
# Accessing 5th index
print("Value at 5th index: ", arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [33]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[43 32  9 42]
 [39 51 78 75]
 [49 59 87 69]
 [11 78 46 44]
 [40 43 20 42]]


In [34]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  [49 59 87 69]


In [35]:
# Accessing value at 2, 1 index
print("Accessing Value using Way-1: ", arr[2][1])

print("Accessing Value using Way-2: ", arr[2, 1]) 
# Way-2 syntax can be helpful to access multiple values

Accessing Value using Way-1:  59
Accessing Value using Way-2:  59


In [36]:
# Accesssing multiple values
print(arr[[2, 1], [1, 1]])

[59 51]


#### Data Accessing using `Slicing` in Numpy Array

In [37]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [ 6 40 86  3 50 33 80 18 84 47]
Shape:  (10,)


In [38]:
# print(arr[1:4])

# print(arr[0:-4])

# print(arr[::2])

In [39]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape:  (3, 4)


In [40]:
# # Remember Way-2 for accessing the data in Numpy array
# print(arr[:2, 1:3])

In [41]:
# print(arr[1:2, :])

#### Indexing with Boolean Arrays

In [42]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [ 1 80 68 22 54 68 61 57 97 25]
Shape:  (10,)


In [43]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[ 1 68 97 25]


#### Updating Data in Numpy Array

In [44]:
# Updating value in the array

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[94  7 65 88]
 [23 72 58 57]
 [33  9 40 88]
 [48 20 33 52]
 [ 2 90  5 63]]
Updated Array: 
 [[94  7 65 88]
 [23 99 58 57]
 [33  9 40 88]
 [48 20 33 52]
 [ 2 90  5 63]]


## Numpy Flatten and Ravel

In [45]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[16 36 17 28 17 13 19 20 33 38]
 [37 19 15 25 31 16 21 31 15 16]
 [12 27 14 14 37 34 22 27 36 17]
 [16 32 19 19 19 33 14 25 39 19]
 [15 29 35 34 28 23 33 10 12 29]]
Shape:  (5, 10)


In [46]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [16 36 17 28 17 13 19 20 33 38 37 19 15 25 31 16 21 31 15 16 12 27 14 14
 37 34 22 27 36 17 16 32 19 19 19 33 14 25 39 19 15 29 35 34 28 23 33 10
 12 29]
Shape:  (50,)


In [47]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [16 36 17 28 17 13 19 20 33 38 37 19 15 25 31 16 21 31 15 16 12 27 14 14
 37 34 22 27 36 17 16 32 19 19 19 33 14 25 39 19 15 29 35 34 28 23 33 10
 12 29]
Shape:  (50,)


#### Look's like both are performing fatten operation on the array data. But is there any difference between two functions?

In [48]:
# Updating value in the array
print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[16 36 17 28 17 13 19 20 33 38]
 [37 19 15 25 31 16 21 31 15 16]
 [12 27 14 14 37 34 22 27 36 17]
 [16 32 19 19 19 33 14 25 39 19]
 [15 29 35 34 28 23 33 10 12 29]]
Updated Array: 
 [[16 36 17 28 17 13 19 20 33 38]
 [37 99 15 25 31 16 21 31 15 16]
 [12 27 14 14 37 34 22 27 36 17]
 [16 32 19 19 19 33 14 25 39 19]
 [15 29 35 34 28 23 33 10 12 29]]


In [49]:
print("Flatten Array: \n", flatten_arr)

print("Ravel Array: \n", ravel_arr)

Flatten Array: 
 [16 36 17 28 17 13 19 20 33 38 37 19 15 25 31 16 21 31 15 16 12 27 14 14
 37 34 22 27 36 17 16 32 19 19 19 33 14 25 39 19 15 29 35 34 28 23 33 10
 12 29]
Ravel Array: 
 [16 36 17 28 17 13 19 20 33 38 37 99 15 25 31 16 21 31 15 16 12 27 14 14
 37 34 22 27 36 17 16 32 19 19 19 33 14 25 39 19 15 29 35 34 28 23 33 10
 12 29]


#### Observation
Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

## Numpy Reshape

In [50]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[27 28 15 34 17 23 19 21 12 22]
 [22 29 26 31 18 26 20 22 37 29]
 [30 19 32 17 10 31 16 28 16 22]
 [22 27 11 22 39 39 30 11 31 31]
 [35 18 38 24 24 10 19 10 15 21]]
Shape:  (5, 10)


In [51]:
arr_reshaped = arr.reshape(10, 5)

print(arr_reshaped)

[[27 28 15 34 17]
 [23 19 21 12 22]
 [22 29 26 31 18]
 [26 20 22 37 29]
 [30 19 32 17 10]
 [31 16 28 16 22]
 [22 27 11 22 39]
 [39 30 11 31 31]
 [35 18 38 24 24]
 [10 19 10 15 21]]


In [52]:
arr_reshaped = arr.reshape(25, 2)

print(arr_reshaped)

[[27 28]
 [15 34]
 [17 23]
 [19 21]
 [12 22]
 [22 29]
 [26 31]
 [18 26]
 [20 22]
 [37 29]
 [30 19]
 [32 17]
 [10 31]
 [16 28]
 [16 22]
 [22 27]
 [11 22]
 [39 39]
 [30 11]
 [31 31]
 [35 18]
 [38 24]
 [24 10]
 [19 10]
 [15 21]]


In [53]:
# arr_reshaped = arr.reshape(3, 3)

# print(arr_reshaped)

In [54]:
# arr_reshaped = arr.reshape(5, 50)

# print(arr_reshaped)

## Iterating over Numpy Array

#### Iterating over a 1 Dimensional Array

In [16]:
# Randomly generate an array containing values in the range of 10 to 39
import numpy as np

arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [16 21 15 19 23 11 36 34 32 36]
Shape:  (10,)


In [17]:
# Looping over items in the array
for item in arr1d:
    print(item, end=" ")

16 21 15 19 23 11 36 34 32 36 

#### Iterating over a 2 Dimensional Array

In [18]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr2d = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr2d)

print("Shape: ", arr2d.shape)

Numpy Array: 
 [[35 12 28 34 13 36 17 14 27 33]
 [31 20 38 29 23 13 22 35 35 28]
 [16 12 16 13 20 19 20 12 19 27]
 [30 35 26 16 31 23 31 18 27 39]
 [35 28 17 12 20 26 27 21 16 36]]
Shape:  (5, 10)


In [19]:
# Looping over rows in the 2d array
for row in arr2d:
    print(row)

[35 12 28 34 13 36 17 14 27 33]
[31 20 38 29 23 13 22 35 35 28]
[16 12 16 13 20 19 20 12 19 27]
[30 35 26 16 31 23 31 18 27 39]
[35 28 17 12 20 26 27 21 16 36]


In [20]:
# Looping over each item in the 2d array
for item in arr2d.ravel():
    print(item, end=" ")

35 12 28 34 13 36 17 14 27 33 31 20 38 29 23 13 22 35 35 28 16 12 16 13 20 19 20 12 19 27 30 35 26 16 31 23 31 18 27 39 35 28 17 12 20 26 27 21 16 36 

#### Iterating using `np.nditer()`

In [21]:
for item in np.nditer(arr1d):
    print(item, end=' ')

16 21 15 19 23 11 36 34 32 36 

In [22]:
for item in np.nditer(arr2d):
    print(item, end=' ')

35 12 28 34 13 36 17 14 27 33 31 20 38 29 23 13 22 35 35 28 16 12 16 13 20 19 20 12 19 27 30 35 26 16 31 23 31 18 27 39 35 28 17 12 20 26 27 21 16 36 

In [23]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [16 21 15 19 23 11 36 34 32 36]


ValueError: assignment destination is read-only

In [24]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d, op_flags=['readwrite']):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [16 21 15 19 23 11 36 34 32 36]
Updated Array [16  0 15 19  0 11  0  0  0  0]


**Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Using a Loop)**

In [60]:
# Code

**Exercise: Given an array [1, -10, 2, 3, 0, 6], print the array in this order [0, 6, -10, 2, 1, 3]**

In [ ]:
# Code

## Python Operators on Numpy Array

In [61]:
# We can apply any python operator on Numpy Array.
# It will perform the operation on each element of a numpy array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

Original Array: 
 [[1 2 3]
 [4 5 6]]


In [62]:
print(x + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [63]:
print(x % 2)

[[1 0 1]
 [0 1 0]]


In [64]:
print(x >= 3)

[[False False  True]
 [ True  True  True]]


In [65]:
print(x % 2 == 0)

[[False  True False]
 [ True False  True]]


**Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Without using a Loop)**

In [66]:
# Code

**Exercise: Write a program to filter the values from the array based on below mentioned conditions:  
Either value should be divisible by 5.  
(or) value should be an odd number and factor of 7.**

In [ ]:
# Code

## Numpy Maths

Reference: https://numpy.org/doc/stable/reference/routines.math.html

In [67]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [68]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))

print("Exponent: ", np.exp(arr))

print("Trigonometric Sin: ", np.sin(arr))

print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [69]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [2]:
# Matrix Multiplication
import numpy as np

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


In [71]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


In [72]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


## Numpy Statistics

In [73]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise

print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Array: 
 [1 2 3 4]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [74]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise

print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [75]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [76]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Maximum:  6
Mean:  3.5
Median:  3.5
Variance:  2.9166666666666665
Std Dev:  1.707825127659933


In [77]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

**Explore the following functions:  
np.insert()  
np.append()  
np.delete()**

## Miscellaneous Topics

#### Linspace

In [78]:
# Syntax => np.linspace(begin, end, # of elements)

print(np.linspace(1, 5, 9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [79]:
print(np.linspace(10, 13, 6))

[10.  10.6 11.2 11.8 12.4 13. ]


#### Sorting

In [80]:
import numpy as np

arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[99 77 86 65 76 96 63 54 81 72]
 [69 75 90 61 85 53 95 51 94 51]
 [84 72 70 79 71 97 85 90 61 58]
 [93 59 92 70 90 98 85 95 78 75]
 [92 76 86 79 93 75 52 99 58 67]]


In [81]:
np.sort(arr)

array([[54, 63, 65, 72, 76, 77, 81, 86, 96, 99],
       [51, 51, 53, 61, 69, 75, 85, 90, 94, 95],
       [58, 61, 70, 71, 72, 79, 84, 85, 90, 97],
       [59, 70, 75, 78, 85, 90, 92, 93, 95, 98],
       [52, 58, 67, 75, 76, 79, 86, 92, 93, 99]])

In [82]:
# Column Wise Sorting

np.sort(arr, axis = 0)

array([[69, 59, 70, 61, 71, 53, 52, 51, 58, 51],
       [84, 72, 86, 65, 76, 75, 63, 54, 61, 58],
       [92, 75, 86, 70, 85, 96, 85, 90, 78, 67],
       [93, 76, 90, 79, 90, 97, 85, 95, 81, 72],
       [99, 77, 92, 79, 93, 98, 95, 99, 94, 75]])

In [83]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[54, 63, 65, 72, 76, 77, 81, 86, 96, 99],
       [51, 51, 53, 61, 69, 75, 85, 90, 94, 95],
       [58, 61, 70, 71, 72, 79, 84, 85, 90, 97],
       [59, 70, 75, 78, 85, 90, 92, 93, 95, 98],
       [52, 58, 67, 75, 76, 79, 86, 92, 93, 99]])

#### Stacking

In [84]:
arr_1 = np.arange(5,15).reshape(2,5)

print(arr_1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [85]:
arr_2 = np.arange(25,35).reshape(2,5)
print(arr_2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [86]:
np.vstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [87]:
np.hstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Concatenate

In [89]:
np.concatenate([arr_1, arr_2], axis = 0) # concatinating - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [90]:
np.concatenate([arr_1, arr_2], axis = 1) # concatinating - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Append

In [93]:
np.append(arr_1, arr_2, axis = 0) # Appending - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [94]:
np.append(arr_1, arr_2, axis = 1) # Appending - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Where - Process Array Elements Conditionally

Understanding np.where() Syntax 
```python
numpy.where(  
  condition,   # Where True, yield x, otherwise y  
  [x, y, ]     # Values to choose from  
)  
```

In [95]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [98]:
np.where(arr > 64, 0, 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [97]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

#### argsort

In [99]:
import numpy as np

arr = np.array([10, -5, 6, -1])

print("Indexes: ", arr.argsort()) # Returns indexes

print("Sorted Array: ", arr[arr.argsort()])

Indexes:  [1 3 2 0]
Sorted Array:  [-5 -1  6 10]


## Numpy Broadcasting

* Start matching the dimensions backward (Right to Left)
    - Compatible - If same number appears or if one of them is 1
    - Incompatible - Otherwise

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [3]:
# # Run this program

# arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

# arr_2 = np.array([[1], [2]])

# print(arr_1 + arr_2)

In [4]:
# # Run this program

# arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

# arr_2 = np.array([1])

# print(arr_1 + arr_2)

In [5]:
# # Run this program

# arr_1 = np.array([1, 2, 3, 4, 5])

# arr_2 = np.array([1, 2, 3, 4])

# print(arr_1 + arr_2)

In [6]:
# # Run this program

# arr_1 = np.array([[1], [2], [3], [4], [5]])

# arr_2 = np.array([1, 2, 3, 4])

# print(arr_1 + arr_2)

## Reading CSV into Numpy Array

In [12]:
import numpy as np
 
# using loadtxt()
arr = np.loadtxt("data/nyc_weather.csv", delimiter=",", dtype='str')
print(arr)

[['EST' 'Temperature' 'DewPoint' 'Humidity' 'Sea Level PressureIn'
  'VisibilityMiles' 'WindSpeedMPH' 'PrecipitationIn' 'CloudCover'
  'Events' 'WindDirDegrees']
 ['1/1/2016' '38' '23' '52' '30.03' '10' '8' '0' '5' '' '281']
 ['1/2/2016' '36' '18' '46' '30.02' '10' '7' '0' '3' '' '275']
 ['1/3/2016' '40' '21' '47' '29.86' '10' '8' '0' '1' '' '277']
 ['1/4/2016' '25' '9' '44' '30.05' '10' '9' '0' '3' '' '345']
 ['1/5/2016' '20' '-3' '41' '30.57' '10' '5' '0' '0' '' '333']
 ['1/6/2016' '33' '4' '35' '30.5' '10' '4' '0' '0' '' '259']
 ['1/7/2016' '39' '11' '33' '30.28' '10' '2' '0' '3' '' '293']
 ['1/8/2016' '39' '29' '64' '30.2' '10' '4' '0' '8' '' '79']
 ['1/9/2016' '44' '38' '77' '30.16' '9' '8' 'T' '8' 'Rain' '76']
 ['1/10/2016' '50' '46' '71' '29.59' '4' '' '1.8' '7' 'Rain' '109']
 ['1/11/2016' '33' '8' '37' '29.92' '10' '' '0' '1' '' '289']
 ['1/12/2016' '35' '15' '53' '29.85' '10' '6' 'T' '4' '' '235']
 ['1/13/2016' '26' '4' '42' '29.94' '10' '10' '0' '0' '' '284']
 ['1/14/2016' '3