Credits: https://github.com/bansalkanav/Machine_Learning_and_Deep_Learning

## Symmetric Distribution, Skewness, Kurtosis

https://en.wikipedia.org/wiki/Skewness

https://en.wikipedia.org/wiki/Kurtosis

## Numpy

Most powerful numerical processing library in python. Array Oriented computing.

Provides extension package to python for multi dimensional array.

Very efficient.

Scientific computation.

In [2]:
# Install a pip package in the current Jupyter kernel
! pip install numpy

In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4, 5, 6, 7]

print(type(l))

arr = np.array(l)

print(type(arr))

print("List: ", l)

print("NP Array: ", arr)

<class 'list'>
<class 'numpy.ndarray'>
List:  [1, 2, 3, 4, 5, 6, 7]
NP Array:  [1 2 3 4 5 6 7]


In [3]:
# Creating a simple array in numpy

arr = np.array([1, 2, 3, 4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr = np.arange(10)

print(arr)

print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


# But WHY numpy, when we already have  lists?

In [5]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i];

Wall time: 862 ms


In [11]:
%%time

arr = np.arange(1000000)

arr = arr * arr

Wall time: 8.1 ms


## Creating an Array

In [19]:
arr = np.array([1, 2, 3, 4])

# Print number of dimensions
print(arr.ndim)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)

# Print item size in byte of each element
print(arr.itemsize)

1
(4,)
4
int32
4


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

# Print number of dimensions
print(arr.ndim)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)

# Print item size in byte of each element
print(arr.itemsize)

# Print diagonal elements
print(np.diag(arr))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int32
4
[1 5]


## Functions for creating array

In [6]:
arr = np.ones((3, 3))

print(arr)

print(arr.dtype)

print(arr.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
float64
8


In [22]:
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr = np.eye(3, 2)

print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [5]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [7]:
arr = np.arange(1, 10, 2)

print(arr)

[1 3 5 7 9]


In [1]:
# CONTINUE

############################################################################
############################################################################
############################################################################
############################################################################
############################################################################
############################################################################
############################################################################
############################################################################
############################################################################


## Numpy Random Numbers

1. **np.random.rand** - generates an array with random numbers that are uniformly distribute between 0 and 1.
2. **np.random.randn** - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
3. **np.random.randint** - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
4. **np.random.uniform** - generates an array with random numbers (float) between given numbers.

In [37]:
arr = np.random.rand(5)

print(arr)

[0.48546201 0.23828849 0.16362295 0.55299602 0.26479966]


In [31]:
print(np.random.rand(10,2))

[[0.03275144 0.12557566]
 [0.18366116 0.84414952]
 [0.82488214 0.05911469]
 [0.99818462 0.91341828]
 [0.50302103 0.65583855]
 [0.60819107 0.84526777]
 [0.87068416 0.84758616]
 [0.03155027 0.37637027]
 [0.2183761  0.86900468]
 [0.53180603 0.52914191]]


In [35]:
print(np.random.randn(5))

[-0.17771456  2.262273   -0.1795009  -0.88480697  0.46809213]


In [36]:
print(np.random.randn(5, 4))

[[ 0.22510303  0.49453151  2.62598289 -0.34477684]
 [ 2.02629573 -0.13759845 -0.92145606 -1.74795121]
 [-0.1601793   0.54777569 -0.81307967 -0.53689182]
 [-0.08214828 -0.73267149  0.74801456 -0.16970734]
 [ 0.5608122   0.87529081  0.1827234   0.19008378]]


In [38]:
# one random integer between 0 to 9

print(np.random.randint(10))

7


In [39]:
print(np.random.randint(10, size = (5, 4)))

[[2 2 8 8]
 [5 9 0 3]
 [0 4 3 9]
 [7 0 3 5]
 [1 1 2 1]]


In [40]:
print(np.random.randint(10, 40, size = (5, 4)))

[[21 15 19 15]
 [35 12 19 34]
 [18 20 26 23]
 [27 21 25 30]
 [18 23 24 22]]


In [43]:
print(np.random.uniform(10))

7.784877348813762


In [45]:
print(np.random.uniform(10, size = (5, 4)))

[[4.63613964 7.22399178 7.15426935 5.15676131]
 [6.65770435 5.35454325 4.41941985 6.40017714]
 [2.31004626 1.34704793 2.66487756 1.17181242]
 [1.52791422 7.62024039 9.41457367 4.08850108]
 [9.37224004 3.67813839 6.62885029 3.47736653]]


In [41]:
print(np.random.uniform(10, 40, size = (5, 4)))

[[36.70355067 37.86606544 28.68039213 15.30657285]
 [10.47238706 22.24925592 27.81237868 35.178991  ]
 [10.56596673 30.4894689  21.52194652 16.74658882]
 [31.42917073 16.8469729  18.13256088 36.37225259]
 [33.07878778 33.94953608 10.43614633 12.89871661]]


## Numpy Indexing

In [5]:
# Why? (Broadcasting)

arr = 3 * np.arange(10)

print(arr)

print(arr[2])

[ 0  3  6  9 12 15 18 21 24 27]
6


In [6]:
print(arr[10])

IndexError: index 10 is out of bounds for axis 0 with size 10

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1, 2])

6


In [9]:
arr[1, 2] = 99

print(arr)

[[ 1  2  3]
 [ 4  5 99]]


## Numpy Slicing

In [10]:
arr = np.arange(10)

print(arr[::2])

print(arr[1:4])

print(arr[0:-4])

[0 2 4 6 8]
[1 2 3]
[0 1 2 3 4 5]


In [11]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arr[:2, 1:3])

[[2 3]
 [6 7]]


In [12]:
print(arr[1:2, :])

[[5 6 7 8]]


In [13]:
arr = np.array([[1,2],[3,4],[5,6]])

print(arr[2, 1])

print(arr[[0, 1, 2], [0, 1, 0]])

6
[1 4 5]


## Numpy Maths

In [16]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print(np.add(x, y))

print('*'*40)

print(np.subtract(x, y))

print('*'*40)

print(np.multiply(x, y))

print('*'*40)

print(np.divide(x, y))

[[ 6  8]
 [10 12]]
****************************************
[[-4 -4]
 [-4 -4]]
****************************************
[[ 5 12]
 [21 32]]
****************************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
# Matrix Multiplication

print(np.matmul(x, y))

print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [18]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))

print(np.sum(x, axis=0)) # Column Wise

print(np.sum(x, axis=1)) # Row wise

10
[4 6]
[3 7]


In [19]:
print(np.min(x))

print(np.max(x))

1
4


In [20]:
print(x)

print('*'*40)

print(x.T)

[[1 2]
 [3 4]]
****************************************
[[1 3]
 [2 4]]


In [7]:
np.exp(1)

2.718281828459045

In [8]:
np.exp(2)

7.38905609893065

## Numpy Statistics

In [52]:
x = np.array([160, 180, 146, 162, 184, 180])

In [54]:
print(np.max(x))

print(np.min(x))

184
146


In [53]:
print(np. mean(x))

print(np.median(x))

print(np.var(x))

print(np.std(x))

168.66666666666666
171.0
187.55555555555557
13.695092389449425


In [55]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

## Numpy Reshape

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 50, 5)

print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [4]:
arr2d = arr.reshape(2, 5)

print(arr2d)

[[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [5]:
arr2d = arr.reshape(5, 2)

print(arr2d)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]


In [6]:
arr2d = arr.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [2]:
arr = np.arange(5, 50)

print(arr.shape)

(45,)


In [3]:
print(arr.reshape(5, 9))

[[ 5  6  7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49]]


In [4]:
print(arr.reshape(3, 3, 5))

[[[ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [5]:
print(arr.flatten())

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Miscellaneous Topics

#### Linspace

In [13]:
# Syntax => np.linspace(begin, end, # of elements)

print(np.linspace(1, 5, 9))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [14]:
print(np.linspace(10,13,6))

[10.  10.6 11.2 11.8 12.4 13. ]


#### Sorting

In [7]:
arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[89 98 58 70 88 69 84 88 81 52]
 [57 76 83 53 60 92 82 81 74 70]
 [75 89 84 86 81 62 84 54 69 51]
 [87 98 76 72 87 73 52 84 61 57]
 [77 94 90 53 60 58 88 77 96 56]]


In [8]:
# Column Wise Sorting

np.sort(arr, axis = 0)

array([[57, 76, 58, 53, 60, 58, 52, 54, 61, 51],
       [75, 89, 76, 53, 60, 62, 82, 77, 69, 52],
       [77, 94, 83, 70, 81, 69, 84, 81, 74, 56],
       [87, 98, 84, 72, 87, 73, 84, 84, 81, 57],
       [89, 98, 90, 86, 88, 92, 88, 88, 96, 70]])

In [9]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[52, 58, 69, 70, 81, 84, 88, 88, 89, 98],
       [53, 57, 60, 70, 74, 76, 81, 82, 83, 92],
       [51, 54, 62, 69, 75, 81, 84, 84, 86, 89],
       [52, 57, 61, 72, 73, 76, 84, 87, 87, 98],
       [53, 56, 58, 60, 77, 77, 88, 90, 94, 96]])

#### Stacking

In [11]:
arr1 = np.arange(5,15).reshape(2,5)
print(arr1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [12]:
arr2 = np.arange(25,35).reshape(2,5)
print(arr2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [13]:
np.vstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [18]:
np.hstack([arr1, arr2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Concatenate

In [20]:
np.concatenate([arr1, arr2], axis = 0) # adding row wise

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [16]:
np.concatenate([arr1, arr2], axis = 1) # adding Column wise

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Append

In [21]:
np.append(arr1, arr2, axis = 0) # adding row wise

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [22]:
np.append(arr1, arr2, axis = 1) # adding Column wise

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

#### Where

In [24]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [27]:
np.where(arr > 64, 0, arr)

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [28]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

## Numpy Broadcasting

* Start matching the dimensions backward (Right to Left)
    - Compatible - If same number appears or if one of them is 1
    - Incompatible - Otherwise

In [2]:
import numpy as np

In [3]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [4]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([[1], [2]])

print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]


In [5]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1])

print(arr_1 + arr_2)

[[2 3 4]
 [5 6 7]]


In [6]:
arr_1 = np.array([1, 2, 3, 4, 5])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [7]:
arr_1 = np.array([[1], [2], [3], [4], [5]])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
