Credits: https://github.com/bansalkanav/Machine_Learning_and_Deep_Learning

# **High Speed Numerical Array Computation using NumPy Module**

NumPy (**Num**erical **Py**thon) is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures. 

### **What's covered in this notebook?**
1. Introduction to NumPy
	- What is an "array"?
	- Installing NumPy
	- How to import NumPy & Creating NumPy Array
	- Why NumPy when we already have lists?
	- NumPy vs Lists in action
	- NumPy Array Axis
	- NumPy Array Restrictions
2. NumPy Array's Attributes/Properties
3. Datatypes in Numpy
4. Functions for creating NumPy Array **(Create Operation)**
	- Creating NumPy Array with arange()
	- Creating NumPy Array with ones()
	- Creating NumPy array with zeros()
	- Creating NumPy array with eye()
	- Creating NumPy array with linspace()
5. Numpy Random Numbers
	- np.random.rand()
	- np.random.randn()
	- np.random.randint()
	- np.random.uniform()
6. Data Accessing from NumPy Array - Indexing and Slicing **(Read Operation)**
	- Using Indexing
    - Using Indexing with Boolean Arrays
	- Using Boolean Masking with Conditions
	- Using Boolean Masking with Multiple Conditions
	- Using Slicing
		- Copy vs View
        - Relation to Shallow vs Deep Copy
		- How to tell if the array is a view or a copy?
		- Few more slicing examples
7. Updating Data in Numpy Array **(Update Operation)**
    - Updating a Single Element
    - Updating Multiple Elements
    - Updating an Entire Row
    - Updating an Entire Column
8. Deleting Elements from the NumPy Array **(Delete Operation)**
	- Deleting a Single Element
	- Deleting Multiple Elements
	- Deleting Row in a 2D Array
	- Deleting Column in a 2D Array
    - Replacing with np.nan
9. Insert Elements in NumPy Array
	- Inserting in a 1D NumPy Array
	- Inserting Multiple Values in 1D Array
	- Inserting a Row in a 2D NumPy Array
	- Inserting a Column in a 2D NumPy Array
10. Changing the NumPy Array Shape
	- Numpy Flatten and Ravel
	- Flatten vs Ravel
	- Numpy Reshape
	- Transpose of NumPy Array
11. Iterating over NumPy Array
	- Iterating over a 1 Dimensional Array
	- Iterating over a 2 Dimensional Array
	- Iterating using np.nditer()
12. Operations on NumPy Array
	- Basic Array Operations
	- NumPy Mathematical Operations
	- NumPy Matrix Multiplication
	- NumPy Statistics
	- Get Diagonal Elements
	- Broadcasting
	- Broadcasting Between Arrays of Different Shape
13. Miscellaneous Topics
	- Reverse an array
	- Getting Unique Items and Count
	- Sorting
	- Stacking
	- Concatenate
	- Append
	- Process Array Elements Conditionally using where()
	- argsort(), argmin() and argmax()
14. Reading CSV into NumPy Array

## **Introduction to NumPy**

### **What is an "array"?**

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a "one-dimensional" array like a list:<br />
<img width="400" height="400" src="images/one_d_array.png"><br />


A two-dimensional array would be like a table:<br />
<img width="400" height="400" src="images/two_d_array.png"><br />


A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages. In NumPy, this idea is generalized to an arbitrary number of dimensions, and so the fundamental array class is called ndarray: it represents an "N-dimensional array".

### **Installing NumPy**
```python
! pip install numpy
```

In [1]:
# # Install a pip package in the current Jupyter kernel
# ! pip install numpy

### **How to import NumPy & Creating NumPy Array**
```python
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
```

In [2]:
# Creating a simple array in numpy
import numpy as np

arr = np.array([1, 2, 3, 4])

print(type(arr))

print("Numpy Array: ", arr)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4]


### **Why NumPy when we already have lists?**
Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

Depending on the characteristics of the data and the types of operations that need to be performed, other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory consumption, and offer a high-level syntax for performing a variety of common processing tasks. NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

Other reasons:
- Most powerful numerical processing library in python. Array Oriented computing.
- Provides extension package to python for multi dimensional array.
- Very efficient.
- Scientific computation.

### **NumPy vs Lists in action**

In [3]:
%%time

lst = list(range(1000000))

for i in range(1000000):
    lst[i] *= lst[i]

CPU times: user 109 ms, sys: 7.16 ms, total: 116 ms
Wall time: 115 ms


In [4]:
%%time

arr = np.arange(1000000)

arr = arr * arr

CPU times: user 3.66 ms, sys: 5.56 ms, total: 9.22 ms
Wall time: 5.81 ms


### **NumPy Array Axis**
In NumPy, a dimension of an array is sometimes referred to as an "axis". This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. 

For instance, the array **arr** could represent three points, each lying within a four-dimensional space, but a has only two "axes".

In NumPy, "axis" helps determine the direction of operations in a multi-dimensional array.

### **NumPy Array Restrictions**
Most NumPy arrays have some restrictions. For instance:
- All elements of the array must be of the same type of data.
- Once created, the total size of the array can't change.
- The shape must be "rectangular", not "jagged"; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

## **NumPy Array's Attributes/Properties**

The important attributes of an ndarray object are:

**ndarray.ndim**  
the number of axes (dimensions) of the array.

**ndarray.shape**  
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

**ndarray.size**  
the total number of elements of the array. This is equal to the product of the elements of shape.

**ndarray.dtype**  
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

**ndarray.itemsize**  
the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

**ndarray.data**  
the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print Size
print("Size: ", arr.size)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

# Print the databuffer of the numpy array
print("Data: ", arr.data)

Array: 
 [1 2 3 4]
Shape:  (4,)
Size:  4
Data Type:  int64
Item Size:  8
Dimensionality:  1
Data:  <memory at 0x1092b9280>


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print Size
print("Size: ", arr.size)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Size:  6
Data Type:  int64
Item Size:  8
Dimensionality:  2


In [7]:
# Let's put all the attributes in a function

def array_attributes(arr):
    # Print shape
    print("Shape: ", arr.shape)

    # Print Size
    print("Size: ", arr.size)

    # Print datatype
    print("Data Type: ", arr.dtype)
    
    # Print item size in byte of each element
    print("Item Size: ", arr.itemsize)
    
    # Print the dimensionality of the numpy array
    print("Dimensionality: ", arr.ndim)


array_attributes(arr)

Shape:  (2, 3)
Size:  6
Data Type:  int64
Item Size:  8
Dimensionality:  2


## **Datatypes in Numpy**

Every NumPy array has a data type that defines the kind of values it holds. Unlike Python, where integers and floats are flexible, NumPy enforces fixed-size data types for performance.

```python
# Specifying a Data Type
arr = np.array([1, 2, 3], dtype=np.int16)  
print(arr.dtype)

# Output: int16
```

Below is a list of all data types in NumPy:
| **Category**     | **Description**                         | **Example Data Types** |
|------------------|---------------------------------------|----------------------|
| **Integer**      | Whole numbers                        | `int8, int16, int32, int64` |
| **Unsigned Int** | Non-negative whole numbers          | `uint8, uint16, uint32, uint64` |
| **Floating-Point** | Decimal numbers                     | `float16, float32, float64, float128` |
| **Complex Numbers** | Numbers with real + imaginary parts | `complex64, complex128` |
| **Boolean**      | True/False                           | `bool` |
| **String**       | Fixed-size text                      | `S` (Byte String) or `U` (Unicode String) |
| **Object**       | Python objects (slowest)             | `object` |
| **Datetime**     | Date & time values                   | `datetime64` |
| **Timedelta**    | Differences between datetime64 values | `timedelta64` |

---


In [8]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='float16')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2. 1. 4. 5.]
Data Type:  float16


In [9]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='object')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  object


In [10]:
import numpy as np

# S10 means max 10 Bytes
arr = np.array(["Hi", "Hello"], dtype='S10')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [b'Hi' b'Hello']
Data Type:  |S10


In [11]:
import numpy as np

# U10 means max 5 Characters
arr = np.array(["Hi", "Hello", "Hello World"], dtype='U5')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)
# Observe how "Hello World" is trimmed to 5 chars

Array: 
 ['Hi' 'Hello' 'Hello']
Data Type:  <U5


## **Functions for creating NumPy Array (Create Operation)**

### **Creating NumPy Array with arange()**

In [12]:
arr = np.arange(10)

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [0 1 2 3 4 5 6 7 8 9]
Shape:  (10,)
Size:  10
Data Type:  int64
Item Size:  8
Dimensionality:  1


In [13]:
arr = np.arange(1, 10)

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [1 2 3 4 5 6 7 8 9]
Shape:  (9,)
Size:  9
Data Type:  int64
Item Size:  8
Dimensionality:  1


In [14]:
arr = np.arange(1, 10, 2)

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [1 3 5 7 9]
Shape:  (5,)
Size:  5
Data Type:  int64
Item Size:  8
Dimensionality:  1


### **Creating NumPy Array with ones()**

In [15]:
arr = np.ones((3, 3))

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape:  (3, 3)
Size:  9
Data Type:  float64
Item Size:  8
Dimensionality:  2


### **Creating NumPy array with zeros()**

In [16]:
arr = np.zeros((3, 3))

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)
Size:  9
Data Type:  float64
Item Size:  8
Dimensionality:  2


### **Creating NumPy array with eye()**

In [17]:
arr = np.eye(3)

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)
Size:  9
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [18]:
arr = np.eye(3, 2)

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape:  (3, 2)
Size:  6
Data Type:  float64
Item Size:  8
Dimensionality:  2


### **Creating NumPy array with linspace()**

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval.

In [19]:
arr = np.linspace(0, 10, num=5)

print("Array: \n", arr)

# Print array attributes
array_attributes(arr)

Array: 
 [ 0.   2.5  5.   7.5 10. ]
Shape:  (5,)
Size:  5
Data Type:  float64
Item Size:  8
Dimensionality:  1


## **Numpy Random Numbers**

1. **np.random.rand** - generates an array with random numbers that are uniformly distribute between 0 and 1.
2. **np.random.randn** - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
3. **np.random.randint** - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
4. **np.random.uniform** - generates an array with random numbers (float) between given numbers.

### **np.random.rand()**

In [20]:
# Randomly generate an array from uniform distribution
import numpy as np

arr = np.random.rand(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [0.61924207 0.02350491 0.45167925 0.43561707 0.64401997]


In [21]:
# Randomly generate an array with 10 rows and 2 columns
arr = np.random.rand(10, 2)

print("Numpy Array generated randomly from uniform distribution: \n", arr)

Numpy Array generated randomly from uniform distribution: 
 [[0.77542486 0.84701528]
 [0.60083613 0.6932673 ]
 [0.98204032 0.44824252]
 [0.96736393 0.54928509]
 [0.85394339 0.26397601]
 [0.26454279 0.06106986]
 [0.9135225  0.91151665]
 [0.63562048 0.81944516]
 [0.22784294 0.66419756]
 [0.51165315 0.98366676]]


### **np.random.randn()**

In [22]:
# Randomly generate an array from normal distribution
import numpy as np

arr = np.random.randn(5)

print("Numpy Array: \n", arr)

Numpy Array: 
 [ 0.10922984  0.66494462 -1.02151471  0.7517107   0.82982111]


In [23]:
# Randomly generate an array with 5 rows and 4 columns
arr = np.random.randn(5, 4)

print("Numpy Array generated randomly from normal distribution: \n", arr)

Numpy Array generated randomly from normal distribution: 
 [[ 0.55424826  1.91835358 -0.30077282 -0.63927294]
 [-1.92707555  0.27310015 -0.47243613  1.60108617]
 [ 0.46891261  0.03688756  0.42967588 -1.26153481]
 [-0.71186673 -0.73268077 -1.36936744 -0.22433065]
 [-1.35003216 -1.28740458  0.74618818 -1.4937959 ]]


### **np.random.randint()**

In [24]:
# Generate one random integer between 0 to 9

value = np.random.randint(10)

print(value)

0


In [25]:
# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[5 0 9 7]
 [6 2 7 2]
 [5 9 0 7]
 [7 5 5 8]
 [9 2 3 5]]


In [26]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[25 30 27 12 24 31 26 16 37 25]
 [32 36 17 29 24 28 13 27 25 23]
 [11 19 24 30 21 31 32 36 38 25]
 [13 20 28 34 17 39 37 28 28 30]
 [34 38 29 16 20 11 34 19 35 23]]


### **np.random.uniform()**

In [27]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)

print(value)

7.117122301143068


In [28]:
# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[4.27397249 6.09431028 1.49809159 9.43090481]
 [5.50482099 2.27929328 4.10875855 4.29668532]
 [3.0674836  7.30639759 5.69527361 8.44306273]
 [9.87510842 3.5687462  2.82331719 9.42781398]
 [1.84333091 3.4934759  7.29966125 5.14888261]]


In [29]:
# Randomly generate a 5*3 array containing values in the range of 10 to 40
arr = np.random.uniform(10, 40, size = (5, 3))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[37.4163456  27.66715311 25.54270931]
 [25.00016057 10.3221954  24.30808022]
 [37.71853752 25.46086984 17.63512983]
 [13.1607837  13.60052672 20.13661993]
 [13.48134942 38.4725275  23.84156549]]


## **Data Accessing from NumPy Array - Indexing and Slicing (Read Operation)**

Since data in numpy array is **stored sequentially**, it is possible to access the data with the help of **Indexing** and **Slicing** operation. NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, **arrays can be indexed by arrays of integers and arrays of booleans**.

### **Using `Indexing`**

It is familiar practice in mathematics to refer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second to last. This generalizes to arrays with any number of dimensions.

**Syntax to access element in 1d array**
```python
# Access element in 1d array
arr[indx]
```

**Syntax to access element in 2d array**
```python
# Way 1: Access element in 2d array
arr[row_indx][col_indx]

# Way 2: This is a better way
arr[row_indx, col_indx]

# Access multiple elements using above syntax
arr[[list_of_row_indx], [list_of_col_indx]]
```



In [30]:
# Randomly generating 1 dimensional array
arr = np.random.randint(100, size = (5, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [28 73 64 65 11]
Shape:  (5,)


In [31]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  64


In [32]:
# Accessing 5th index
print("Value at 5th index: ", arr[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [33]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Numpy Array: \n", arr)

Numpy Array: 
 [[43 93 14 91]
 [79 80 33 22]
 [ 8 60 91 67]
 [23 20 31 86]
 [94 65 75 66]]


In [34]:
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Value at 2nd index:  [ 8 60 91 67]


In [35]:
# Accessing value at 2, 1 index
print("Accessing Value using Way-1: ", arr[2][1])

print("Accessing Value using Way-2: ", arr[2, 1]) 
# Way-2 syntax can be helpful to access multiple values

Accessing Value using Way-1:  60
Accessing Value using Way-2:  60


In [36]:
# Accesssing multiple values
print(arr[[2, 1], [1, 1]])

[60 80]


### **Using Indexing with Boolean Arrays**

In [37]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [18 90 92 11 88 55 78 19  7 38]
Shape:  (10,)


In [38]:
idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

[18 55  7 38]


### **Using Boolean Masking with Conditions**

Boolean Masking is a technique in NumPy that allows you to filter elements of an array based on a condition. Instead of using loops, you can use boolean arrays (masks) to select specific values.

In [39]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Create a boolean mask

print(mask)

[False False  True  True  True]


In [40]:
filtered_arr = arr[mask]  # Apply mask

print(filtered_arr)

[30 40 50]


### **Using Boolean Masking with Multiple Conditions**
We can combine multiple conditions using:
- & is used instead of and
- | is used instead of or
- ~ is used for negation

In [41]:
arr = np.array([5, 10, 15, 20, 25, 30])

mask = (arr > 10) & (arr < 25)  # Select numbers between 10 and 25

print(arr[mask])

[15 20]


In [42]:
# Real-time use case by removing null values
data = np.array([45, np.nan, 78, 56, np.nan, 89])

# Remove NaN values
clean_data = data[~np.isnan(data)]

print(clean_data)

[45. 78. 56. 89.]


### **Using `Slicing`**

Like the original list, Python slice notation can also be used for indexing.

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

#### **Copy VS View**

**Copy**  
When a new array is created by duplicating the data buffer as well as the metadata, it is called a copy. Changes made to the copy do not reflect on the original array. Making a copy is **slower and memory-consuming** but sometimes necessary. A copy can be forced by using **ndarray.copy()**.

**View**  
A view is a new array object that shares the same data as the original array. Any modifications to the view will affect the original array, and vice versa. A view can be forced through the **ndarray.view()** method.

Think of a view in NumPy like a window into the same data. It doesn't create a new copy; it just lets you look at the original array in a different way. This makes view **faster and efficient for memory management**.

### **Relation to Shallow vs Deep Copy**
| Concept | NumPy Term | Behavior |
|---------|-----------|----------|
| **Shallow Copy** | **View** | Shares memory, changes reflect in both |
| **Deep Copy** | **Copy** | Creates new memory, changes are independent |


In [43]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [ 8 55 27 99 66 43 37  2 80 47]
Shape:  (10,)


In [44]:
arr_slice = arr[1:4]

print("Array Slice Before:", arr_slice)

# Updating the arr_slice element at index 1
arr_slice[1] = 99999

print("Array Slice After:", arr_slice)
print()
print("Original Array:", arr)

Array Slice Before: [55 27 99]
Array Slice After: [   55 99999    99]

Original Array: [    8    55 99999    99    66    43    37     2    80    47]


#### **How to tell if the array is a view or a copy?**

The **base** attribute of the ndarray makes it easy to tell if an array is a view or a copy. The base attribute of a view returns the original array while it returns None for a copy.

In [45]:
print(arr.base) # base attribute of copy returns None

print(arr_slice.base) # base attribute of view returns the original array

None
[    8    55 99999    99    66    43    37     2    80    47]


#### **Few more slicing examples**

In [46]:
# print(arr[1:4])

# print(arr[0:-4])

# print(arr[::2])

In [47]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape:  (3, 4)


In [48]:
# # Remember Way-2 for accessing the data in Numpy array
# print(arr[:2, 1:3])

In [49]:
# print(arr[1:2, :])

## **Updating Data in Numpy Array (Update Operation)**

Remember that **numpy array's are mutable**. i.e. Data stored in numpy array can be updated/changed.

### **Updating a Single Element**

In [50]:
# Updating value in the array
import numpy as np

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

# Update a single element
arr[1, 1] = 9999

print("Updated Array: \n", arr)

Original Array: 
 [[48  0 72 12]
 [86 33 70 43]
 [86 84  8 50]
 [23 45 84 67]
 [30 42  8 55]]
Updated Array: 
 [[  48    0   72   12]
 [  86 9999   70   43]
 [  86   84    8   50]
 [  23   45   84   67]
 [  30   42    8   55]]


### **Updating Multiple Elements**

In [51]:
# Update a multiple elements

arr[[0, 4], [0, 1]] = [8888, 7777]

print("Updated Array: \n", arr)

Updated Array: 
 [[8888    0   72   12]
 [  86 9999   70   43]
 [  86   84    8   50]
 [  23   45   84   67]
 [  30 7777    8   55]]


### **Updating an Entire Row**

In [52]:
# Update an entire row

arr[0] = [100, 200, 300, 400]

print("After updating row 0:\n", arr)

After updating row 0:
 [[ 100  200  300  400]
 [  86 9999   70   43]
 [  86   84    8   50]
 [  23   45   84   67]
 [  30 7777    8   55]]


### **Updating an Entire Column**

In [53]:
# Update an entire column

arr[:, 2] = [999, 888, 777, 666, 555]

print("After updating column 2:\n", arr)

After updating column 2:
 [[ 100  200  999  400]
 [  86 9999  888   43]
 [  86   84  777   50]
 [  23   45  666   67]
 [  30 7777  555   55]]


## **Deleting Elements from the NumPy Array (Delete Operation)**

Deleting means removing elements from an array using np.delete().

**Syntax**  
```python
np.delete(arr, indx, axis=None)
```

**Note:**  
    - axis=None for flattened array
    - axis=0 Affects Columns
    - axis=1 Affects Rows

In [54]:
arr = np.array([10, 20, 30, 40, 50])

print("Original Array:\n", arr)

Original Array:
 [10 20 30 40 50]


### **Deleting a Single Element**

In [55]:
# Delete element at index 2

arr_new = np.delete(arr, 2, axis=None)

print("After deleting index 2:", arr_new)

After deleting index 2: [10 20 40 50]


### **Deleting Multiple Elements**

In [56]:
# Delete multiple indices

arr_new = np.delete(arr, [1, 3])

print("After deleting indices 1 and 3:", arr_new)

After deleting indices 1 and 3: [10 30 50]


### **Deleting Row in a 2D Array**

**NumPy does not allow deleting a single element from a 2D array** while preserving its shape because arrays have fixed dimensions. However, you can delete an entire row or column.

In [57]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

print("Original Array:\n", arr2D)

Original Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [58]:
# Delete row 1
arr2D_new = np.delete(arr2D, 1, axis=0)

print("After deleting row 1:\n", arr2D_new)

After deleting row 1:
 [[10 20 30]
 [70 80 90]]


### **Deleting Column in a 2D Array**

In [59]:
# Delete column 2

arr2D_new = np.delete(arr2D, 2, axis=1)

print("After deleting column 2:\n", arr2D_new)

After deleting column 2:
 [[10 20]
 [40 50]
 [70 80]]


### **Replacing with np.nan**

Since deletion isn't allowed while keeping the shape, you can replace the element with a placeholder (like np.nan or 0).

In [60]:
# Replace the element at 1, 1 index with NaN (Not a Number)
arr2D[1, 1] = np.nan

print(arr2D)

ValueError: cannot convert float NaN to integer

**Caution: np.nan works only with float arrays.**

In [61]:
arr2D = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]], dtype="float32")

print("Original Array:\n", arr2D)

Original Array:
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [62]:
# Replace the element at 1, 1 index with NaN (Not a Number)
arr2D[1, 1] = np.nan

print(arr2D)

[[10. 20. 30.]
 [40. nan 60.]
 [70. 80. 90.]]


## **Insert Elements in NumPy Array**

The np.insert() function is used to insert values into a NumPy array at specified positions **without modifying the original array** (it returns a new array). It works on both 1D and multi-dimensional arrays.

**Syntax**
```python
np.insert(arr, index, values, axis=None)
```

**Note:**  
    - axis=None for flattened array
    - axis=0 Affects Columns
    - axis=1 Affects Rows

In [63]:
arr = np.array([10, 20, 30, 40])

print("Original Array:\n", arr)

Original Array:
 [10 20 30 40]


### **Inserting in a 1D NumPy Array**

In [64]:
new_arr = np.insert(arr, 2, 25)  # Insert 25 at index 2

print("After Insertion:", new_arr)

After Insertion: [10 20 25 30 40]


### **Inserting Multiple Values in 1D Array**

In [65]:
new_arr = np.insert(arr, [1, 3], [99, 88])

print("Original Array:\n", arr)
print()
print("After Insertion:", new_arr)

Original Array:
 [10 20 30 40]

After Insertion: [10 99 20 30 88 40]


### **Inserting a Row in a 2D NumPy Array**

In [66]:
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6]])

print("Original Array:\n", arr2D)

Original Array:
 [[1 2 3]
 [4 5 6]]


In [67]:
new_row = [7, 8, 9]

# Insert at row index 1
new_arr = np.insert(arr2D, 1, new_row, axis=0)

print(new_arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


### **Inserting a Column in a 2D NumPy Array**

In [68]:
new_col = [99, 88]

# Insert at column index 1
new_arr = np.insert(arr2D, 1, new_col, axis=1)

print(new_arr)

[[ 1 99  2  3]
 [ 4 88  5  6]]


## **Changing the NumPy Array Shape**

### **Numpy Flatten and Ravel**

In [69]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[10 39 20 37 19 19 33 28 14 20]
 [35 15 19 22 31 20 15 10 37 18]
 [37 36 31 39 26 18 33 33 20 16]
 [31 19 13 16 36 16 33 26 10 15]
 [18 13 13 22 15 24 37 23 18 17]]
Shape:  (5, 10)


In [70]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [10 39 20 37 19 19 33 28 14 20 35 15 19 22 31 20 15 10 37 18 37 36 31 39
 26 18 33 33 20 16 31 19 13 16 36 16 33 26 10 15 18 13 13 22 15 24 37 23
 18 17]
Shape:  (50,)


In [71]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [10 39 20 37 19 19 33 28 14 20 35 15 19 22 31 20 15 10 37 18 37 36 31 39
 26 18 33 33 20 16 31 19 13 16 36 16 33 26 10 15 18 13 13 22 15 24 37 23
 18 17]
Shape:  (50,)


### **Flatten vs Ravel**

Look's like both are performing fatten operation on the array data. But is there any difference between two functions?

In [72]:
# Updating value in the array
print("Original Array: \n", arr)

Original Array: 
 [[10 39 20 37 19 19 33 28 14 20]
 [35 15 19 22 31 20 15 10 37 18]
 [37 36 31 39 26 18 33 33 20 16]
 [31 19 13 16 36 16 33 26 10 15]
 [18 13 13 22 15 24 37 23 18 17]]


In [73]:
flatten_arr[1] = 99

print("Flatten Array: \n", flatten_arr)

print("Original Array: \n", arr)

Flatten Array: 
 [10 99 20 37 19 19 33 28 14 20 35 15 19 22 31 20 15 10 37 18 37 36 31 39
 26 18 33 33 20 16 31 19 13 16 36 16 33 26 10 15 18 13 13 22 15 24 37 23
 18 17]
Original Array: 
 [[10 39 20 37 19 19 33 28 14 20]
 [35 15 19 22 31 20 15 10 37 18]
 [37 36 31 39 26 18 33 33 20 16]
 [31 19 13 16 36 16 33 26 10 15]
 [18 13 13 22 15 24 37 23 18 17]]


In [74]:
ravel_arr[1] = 99

print("Ravel Array: \n", ravel_arr)

print("Original Array: \n", arr)

Ravel Array: 
 [10 99 20 37 19 19 33 28 14 20 35 15 19 22 31 20 15 10 37 18 37 36 31 39
 26 18 33 33 20 16 31 19 13 16 36 16 33 26 10 15 18 13 13 22 15 24 37 23
 18 17]
Original Array: 
 [[10 99 20 37 19 19 33 28 14 20]
 [35 15 19 22 31 20 15 10 37 18]
 [37 36 31 39 26 18 33 33 20 16]
 [31 19 13 16 36 16 33 26 10 15]
 [18 13 13 22 15 24 37 23 18 17]]


**Observation:**  
Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

### **Numpy Reshape**

In [75]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[14 10 12 23 29 28 28 14 25 29]
 [31 12 30 28 39 21 15 19 15 27]
 [33 38 26 24 31 35 10 26 36 37]
 [10 24 24 33 31 34 26 32 16 20]
 [10 25 18 16 14 10 22 32 36 28]]
Shape:  (5, 10)


In [76]:
arr_reshaped = arr.reshape(10, 5)

print(arr_reshaped)

[[14 10 12 23 29]
 [28 28 14 25 29]
 [31 12 30 28 39]
 [21 15 19 15 27]
 [33 38 26 24 31]
 [35 10 26 36 37]
 [10 24 24 33 31]
 [34 26 32 16 20]
 [10 25 18 16 14]
 [10 22 32 36 28]]


In [77]:
arr_reshaped = arr.reshape(25, 2)

print(arr_reshaped)

[[14 10]
 [12 23]
 [29 28]
 [28 14]
 [25 29]
 [31 12]
 [30 28]
 [39 21]
 [15 19]
 [15 27]
 [33 38]
 [26 24]
 [31 35]
 [10 26]
 [36 37]
 [10 24]
 [24 33]
 [31 34]
 [26 32]
 [16 20]
 [10 25]
 [18 16]
 [14 10]
 [22 32]
 [36 28]]


In [78]:
# arr_reshaped = arr.reshape(3, 3)

# print(arr_reshaped)

In [79]:
# arr_reshaped = arr.reshape(5, 50)

# print(arr_reshaped)

### **Transpose of NumPy Array**

In [80]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


## **Iterating over NumPy Array**

### **Iterating over a 1 Dimensional Array**

In [81]:
# Randomly generate an array containing values in the range of 10 to 39
import numpy as np

arr1d = np.random.randint(10, 40, size = (10, ))

print("Numpy Array: \n", arr1d)

print("Shape: ", arr1d.shape)

Numpy Array: 
 [25 33 13 36 33 27 33 35 22 20]
Shape:  (10,)


In [82]:
# Looping over items in the array
for item in arr1d:
    print(item, end=" ")

25 33 13 36 33 27 33 35 22 20 

### **Iterating over a 2 Dimensional Array**

In [83]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr2d = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr2d)

print("Shape: ", arr2d.shape)

Numpy Array: 
 [[38 19 22 19 30 29 23 17 19 36]
 [24 14 36 29 29 18 13 31 38 18]
 [18 14 33 18 35 20 24 10 27 31]
 [19 27 27 18 15 10 25 21 15 25]
 [10 17 24 38 25 24 18 12 14 39]]
Shape:  (5, 10)


In [84]:
# Looping over rows in the 2d array
for row in arr2d:
    print(row)

[38 19 22 19 30 29 23 17 19 36]
[24 14 36 29 29 18 13 31 38 18]
[18 14 33 18 35 20 24 10 27 31]
[19 27 27 18 15 10 25 21 15 25]
[10 17 24 38 25 24 18 12 14 39]


In [85]:
# Looping over each item in the 2d array
for item in arr2d.ravel():
    print(item, end=" ")

38 19 22 19 30 29 23 17 19 36 24 14 36 29 29 18 13 31 38 18 18 14 33 18 35 20 24 10 27 31 19 27 27 18 15 10 25 21 15 25 10 17 24 38 25 24 18 12 14 39 

### **Iterating using `np.nditer()`**

In [86]:
for item in np.nditer(arr1d):
    print(item, end=' ')

25 33 13 36 33 27 33 35 22 20 

In [87]:
for item in np.nditer(arr2d):
    print(item, end=' ')

38 19 22 19 30 29 23 17 19 36 24 14 36 29 29 18 13 31 38 18 18 14 33 18 35 20 24 10 27 31 19 27 27 18 15 10 25 21 15 25 10 17 24 38 25 24 18 12 14 39 

In [88]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [25 33 13 36 33 27 33 35 22 20]


ValueError: assignment destination is read-only

In [89]:
print("Original Array: ", arr1d)

for item in np.nditer(arr1d, op_flags=['readwrite']):
    if item > 20:
        item[...] = (item * 0)
        
print("Updated Array", arr1d)

Original Array:  [25 33 13 36 33 27 33 35 22 20]
Updated Array [ 0  0 13  0  0  0  0  0  0 20]


**Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Using a Loop)**

In [90]:
# Code

**Exercise: Given an array [1, -10, 2, 3, 0, 6], print the array in this order [0, 6, -10, 2, 1, 3]**

In [91]:
# Code

## **Operations on NumPy Array**

### **Basic Array Operations**

This section covers addition, subtraction, multiplication, division, and more.

Arithmetic operators on arrays apply **elementwise**. A new array is created and filled with the result.

In [92]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [93]:
result = data + ones

print(result)

[2 3]


In [94]:
result = data - ones

print(result)

[0 1]


In [95]:
result = data * data

print(result)

[1 4]


In [96]:
result = data / data

print(result)

[1. 1.]


### **NumPy Mathematical Operations**

Reference: https://numpy.org/doc/stable/reference/routines.math.html

All the operations like sqrt(), exp(), sin(), cos(), add(), subtract(), etc... are applied **elementwise**.

In [97]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [98]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))

print("Exponent: ", np.exp(arr))

print("Trigonometric Sin: ", np.sin(arr))

print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [99]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### **NumPy Matrix Multiplication**

In [100]:
# Matrix Multiplication
import numpy as np

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


### **NumPy Statistics**

In [101]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Affects Columns

print("Rowwise Sum: ", np.sum(x, axis=1)) # Affects Rows

Array: 
 [1 2 3 4]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [102]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Affects Columns

print("Rowwise Minimum: ", np.min(x, axis=1)) # Affects Rows

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [103]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [104]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Maximum:  6
Mean:  3.5
Median:  3.5
Variance:  2.9166666666666665
Std Dev:  1.707825127659933


In [105]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

### **Get Diagonal Elements**

In [106]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


### **Broadcasting**

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it "data") might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

```python
dist_in_miles = np.array([1.0, 2.0])
convert_to_km = dist_in_miles * 1.6
```
<img width="500" height="200" src="images/broadcasting.png"><br />

In [107]:
# We can apply any python operator on Numpy Array.
# It will perform the operation on each element of a numpy array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

Original Array: 
 [[1 2 3]
 [4 5 6]]


In [108]:
print(x + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [109]:
print(x % 2)

[[1 0 1]
 [0 1 0]]


In [110]:
print(x >= 3)

[[False False  True]
 [ True  True  True]]


In [111]:
print(x % 2 == 0)

[[False  True False]
 [ True False  True]]


**Exercise: Write a program to generate an array with shape 5*4 at random containing positive integer. Perform an update by replacing all odd numbers with -1. (Without using a Loop)**

In [112]:
# Code

**Exercise: Write a program to filter the values from the array based on below mentioned conditions:  
Either value should be divisible by 5.  
(or) value should be an odd number and factor of 7.**

In [113]:
# Code

### **Broadcasting Between Arrays of Different Shape**

* Start matching the dimensions backward (Right to Left)
    - Compatible - If same number appears or if one of them is 1
    - Incompatible - Otherwise

In [114]:
import numpy as np

In [115]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [116]:
# # Run this program

# arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

# arr_2 = np.array([[1], [2]])

# print(arr_1 + arr_2)

In [117]:
# # Run this program

# arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

# arr_2 = np.array([1])

# print(arr_1 + arr_2)

In [118]:
# # Run this program

# arr_1 = np.array([1, 2, 3, 4, 5])

# arr_2 = np.array([1, 2, 3, 4])

# print(arr_1 + arr_2)

In [119]:
# # Run this program

# arr_1 = np.array([[1], [2], [3], [4], [5]])

# arr_2 = np.array([1, 2, 3, 4])

# print(arr_1 + arr_2)

## **Miscellaneous Topics**

### **Reverse an array**

In [120]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr)

print('Reversed Array:\n', reversed_arr)


Reversed Array:
 [8 7 6 5 4 3 2 1]


In [121]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr = np.flip(arr_2d)

print('Reversed Array:\n', reversed_arr)

Reversed Array:
 [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [122]:
# Reverse only the rows
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr_rows = np.flip(arr_2d, axis=0) # Affects Columns

print('Reversed Array:\n', reversed_arr_rows)

Reversed Array:
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### **Getting Unique Items and Count**

In [123]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4], [9, 10, 11, 12]])

print(a_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


In [124]:
unique_values = np.unique(a_2d)

print("Unique Values:\n", unique_values)

Unique Values:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [125]:
unique_values, indices_list = np.unique(a_2d, return_index=True)

print("Unique Values:\n", unique_values)
print()
print("Indices:", indices_list)

Unique Values:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Indices: [ 0  1  2  3  4  5  6  7 12 13 14 15]


**Note:** If the axis argument isn’t passed, your 2D array will be flattened.

In [126]:
unique_values, occurrence_count = np.unique(a_2d, return_counts=True)

print("Unique Values:\n", unique_values)
print()
print("Indices:", indices_list)
print()
print("Count:", occurrence_count)

Unique Values:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Indices: [ 0  1  2  3  4  5  6  7 12 13 14 15]

Count: [2 2 2 2 1 1 1 1 1 1 1 1]


In [127]:
unique_rows, indices_list, occurrence_count = np.unique(a_2d, 
                                                   axis=0, 
                                                   return_counts=True, 
                                                   return_index=True) # Affects Columns

print("Unique Values:\n", unique_rows)
print()
print("Indices:", indices_list)
print()
print("Count:", occurrence_count)

Unique Values:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Indices: [0 1 3]

Count: [2 1 1]


### **Sorting**

In [128]:
import numpy as np

arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[76 62 69 63 51 75 75 71 53 93]
 [96 92 81 72 54 52 99 94 96 87]
 [72 84 52 98 50 72 79 61 64 59]
 [86 55 70 83 58 75 93 75 63 57]
 [88 56 98 85 84 53 83 51 84 99]]


In [129]:
np.sort(arr)

array([[51, 53, 62, 63, 69, 71, 75, 75, 76, 93],
       [52, 54, 72, 81, 87, 92, 94, 96, 96, 99],
       [50, 52, 59, 61, 64, 72, 72, 79, 84, 98],
       [55, 57, 58, 63, 70, 75, 75, 83, 86, 93],
       [51, 53, 56, 83, 84, 84, 85, 88, 98, 99]])

In [130]:
# Column Wise Sorting

np.sort(arr, axis = 0) # Affects Columns

array([[72, 55, 52, 63, 50, 52, 75, 51, 53, 57],
       [76, 56, 69, 72, 51, 53, 79, 61, 63, 59],
       [86, 62, 70, 83, 54, 72, 83, 71, 64, 87],
       [88, 84, 81, 85, 58, 75, 93, 75, 84, 93],
       [96, 92, 98, 98, 84, 75, 99, 94, 96, 99]])

In [131]:
# Row Wise Sorting

np.sort(arr, axis = 1) # Affects Rows

array([[51, 53, 62, 63, 69, 71, 75, 75, 76, 93],
       [52, 54, 72, 81, 87, 92, 94, 96, 96, 99],
       [50, 52, 59, 61, 64, 72, 72, 79, 84, 98],
       [55, 57, 58, 63, 70, 75, 75, 83, 86, 93],
       [51, 53, 56, 83, 84, 84, 85, 88, 98, 99]])

### **Stacking**

In [132]:
arr_1 = np.arange(5,15).reshape(2,5)

print(arr_1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [133]:
arr_2 = np.arange(25,35).reshape(2,5)
print(arr_2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [134]:
np.vstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [135]:
np.hstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

### **Concatenate**

In [136]:
np.concatenate([arr_1, arr_2], axis = 0) # concatinating - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [137]:
np.concatenate([arr_1, arr_2], axis = 1) # concatinating - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

### **Append**

In [138]:
np.append(arr_1, arr_2, axis = 0) # Appending - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [139]:
np.append(arr_1, arr_2, axis = 1) # Appending - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

### **Process Array Elements Conditionally using where()**

Understanding np.where() Syntax 
```python
numpy.where(  
  condition,   # Where True, yield x, otherwise y  
  [x, y, ]     # Values to choose from  
)  
```

In [140]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [141]:
np.where(arr > 64, 0, 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [142]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

### **argsort(), argmin() and argmax()**

In NumPy, functions like argsort(), argmin(), and argmax() are used to get the indices of elements rather than their values. These functions are extremely useful when you need to locate specific elements in an array.

In [143]:
import numpy as np

arr = np.array([10, -5, 6, -1])

In [144]:
print("Index of minimum element:", arr.argmin())

Index of minimum element: 1


In [145]:
print("Index of maximum element:", arr.argmax())

Index of maximum element: 0


In [146]:
print("Indexes:", arr.argsort()) # Returns indexes

print("Sorted Array:", arr[ arr.argsort() ])

Indexes: [1 3 2 0]
Sorted Array: [-5 -1  6 10]


## **Reading CSV into NumPy Array**

In [147]:
import numpy as np
 
# using loadtxt()
arr = np.loadtxt("data/nyc_weather.csv", delimiter=",", dtype='str')
print(arr)

[['EST' 'Temperature' 'DewPoint' 'Humidity' 'Sea Level PressureIn'
  'VisibilityMiles' 'WindSpeedMPH' 'PrecipitationIn' 'CloudCover'
  'Events' 'WindDirDegrees']
 ['1/1/2016' '38' '23' '52' '30.03' '10' '8' '0' '5' '' '281']
 ['1/2/2016' '36' '18' '46' '30.02' '10' '7' '0' '3' '' '275']
 ['1/3/2016' '40' '21' '47' '29.86' '10' '8' '0' '1' '' '277']
 ['1/4/2016' '25' '9' '44' '30.05' '10' '9' '0' '3' '' '345']
 ['1/5/2016' '20' '-3' '41' '30.57' '10' '5' '0' '0' '' '333']
 ['1/6/2016' '33' '4' '35' '30.5' '10' '4' '0' '0' '' '259']
 ['1/7/2016' '39' '11' '33' '30.28' '10' '2' '0' '3' '' '293']
 ['1/8/2016' '39' '29' '64' '30.2' '10' '4' '0' '8' '' '79']
 ['1/9/2016' '44' '38' '77' '30.16' '9' '8' 'T' '8' 'Rain' '76']
 ['1/10/2016' '50' '46' '71' '29.59' '4' '' '1.8' '7' 'Rain' '109']
 ['1/11/2016' '33' '8' '37' '29.92' '10' '' '0' '1' '' '289']
 ['1/12/2016' '35' '15' '53' '29.85' '10' '6' 'T' '4' '' '235']
 ['1/13/2016' '26' '4' '42' '29.94' '10' '10' '0' '0' '' '284']
 ['1/14/2016' '3