## Symmetric Distribution, Skewness, Kurtosis

https://en.wikipedia.org/wiki/Skewness

https://en.wikipedia.org/wiki/Kurtosis

## Numpy

Most powerful numerical processing library in python. Array Oriented computing.

Provides extension package to python for multi dimensional array.

Very efficient.

Scientific computation.

In [2]:
# Install a pip package in the current Jupyter kernel
! pip install numpy

In [3]:
import numpy as np

In [3]:
# Creating a simple array in numpy

arr = np.array([1, 2, 3, 4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr = np.arange(10)

print(arr)

print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


# But WHY numpy, when we already have  lists?

In [14]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i];

Wall time: 310 ms


In [19]:
%%time

arr = np.arange(1000000)

arr = arr * arr

Wall time: 4.99 ms


## Creating an Array

In [19]:
arr = np.array([1, 2, 3, 4])

# Print number of dimensions
print(arr.ndim)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)

# Print item size in byte of each element
print(arr.itemsize)

1
(4,)
4
int32
4


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

# Print number of dimensions
print(arr.ndim)

# Print shape
print(arr.shape)

# Print length
print(len(arr))

# Print datatype
print(arr.dtype)

# Print item size in byte of each element
print(arr.itemsize)

# Print diagonal elements
print(np.diag(arr))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2
int32
4
[1 5]


## Functions for creating array

In [21]:
arr = np.ones((3, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
arr = np.zeros((3, 3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
arr = np.eye(3, 2)

print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [5]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr = np.arange(1, 10)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [7]:
arr = np.arange(1, 10, 2)

print(arr)

[1 3 5 7 9]


In [29]:
arr = np.random.random((2, 2))

print(arr)

[[0.75981196 0.79833258]
 [0.44330672 0.74010057]]


In [47]:
print(np.random.random((10,2)))

[[0.91774411 0.76458857]
 [0.40331787 0.68934125]
 [0.54868564 0.1903161 ]
 [0.99323685 0.40397584]
 [0.58870823 0.64395887]
 [0.79400195 0.88951257]
 [0.29977555 0.979015  ]
 [0.57360994 0.46064154]
 [0.92888142 0.83892782]
 [0.11736006 0.43161418]]


In [56]:
print(np.random.randint(1, 10, 10))

[8 4 4 6 7 3 9 1 5 9]


## Numpy Indexing

In [22]:
# Why? (Broadcasting)

# arr = 3 * np.arange(10)

# print(arr)

# print(arr[2])

In [21]:
# print(arr[10])

In [20]:
# arr = np.array([[1, 2, 3], [4, 5, 6]])

# print(arr[1, 2])

In [23]:
# arr[1, 2] = 99

# print(arr)

## Numpy Slicing

In [24]:
# arr = np.arange(10)

# print(arr[::2])

# print(arr[1:4])

# print(arr[0:-4])

In [25]:
# arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# print(arr[:2, 1:3])

In [26]:
# print(arr[1:2, :])

In [27]:
# arr = np.array([[1,2],[3,4],[5,6]])

# print(arr[2, 1])

# print(arr[[0, 1, 2], [0, 1, 0]])

## Numpy Maths

In [16]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print(np.add(x, y))

print('*'*40)

print(np.subtract(x, y))

print('*'*40)

print(np.multiply(x, y))

print('*'*40)

print(np.divide(x, y))

[[ 6  8]
 [10 12]]
****************************************
[[-4 -4]
 [-4 -4]]
****************************************
[[ 5 12]
 [21 32]]
****************************************
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
# Matrix Multiplication

print(np.matmul(x, y))

print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [18]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))

print(np.sum(x, axis=0)) # Column Wise

print(np.sum(x, axis=1)) # Row wise

10
[4 6]
[3 7]


In [19]:
print(np.min(x))

print(np.max(x))

1
4


In [20]:
print(x)

print('*'*40)

print(x.T)

[[1 2]
 [3 4]]
****************************************
[[1 3]
 [2 4]]


In [7]:
np.exp(1)

2.718281828459045

In [8]:
np.exp(2)

7.38905609893065

## Numpy Statistics

In [52]:
x = np.array([160, 180, 146, 162, 184, 180])

In [54]:
print(np.max(x))

print(np.min(x))

184
146


In [53]:
print(np. mean(x))

print(np.median(x))

print(np.var(x))

print(np.std(x))

168.66666666666666
171.0
187.55555555555557
13.695092389449425


In [55]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

## Numpy Broadcasting

* Start matching the dimensions backward (Right to Left)
    - Compatible - If same number appears or if one of them is 1
    - Incompatible - Otherwise

In [8]:
import numpy as np

In [9]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1, 2, 3])

print(arr_1 + arr_2)

[[2 4 6]
 [5 7 9]]


In [10]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([[1], [2]])

print(arr_1 + arr_2)

[[2 3 4]
 [6 7 8]]


In [11]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])

arr_2 = np.array([1])

print(arr_1 + arr_2)

[[2 3 4]
 [5 6 7]]


In [12]:
arr_1 = np.array([1, 2, 3, 4, 5])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [13]:
arr_1 = np.array([[1], [2], [3], [4], [5]])

arr_2 = np.array([1, 2, 3, 4])

print(arr_1 + arr_2)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
